# Generated by Django 4.0.2 on 2022-03-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(blank=True, upload_to='image_slider')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('program_icons', models.ImageField(blank=True, upload_to='programs_icon')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_icons', models.ImageField(blank=True, upload_to='projects_icon')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icons', models.ImageField(blank=True, upload_to='services_icon')),
            ],
        ),
        migrations.CreateModel(
            name='StatsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_name', models.CharField(max_length=100)),
                ('stats_value', models.CharField(max_length=100)),
                ('stats_icons', models.ImageField(blank=True, upload_to='stats_icon')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, upload_to='members_images')),
                ('position', models.CharField(max_length=150)),
                ('member_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.membercategory')),
                ('year_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.year')),
            ],
        ),
    ]
