# Generated by Django 4.0.2 on 2022-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestitle',
            name='icons',
            field=models.ImageField(blank=True, upload_to='services_icon'),
        ),
    ]
