# Generated by Django 4.0.2 on 2022-02-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_servicestitle_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_icons', models.ImageField(blank=True, upload_to='projects_icon')),
            ],
        ),
    ]
