# Generated by Django 4.0.2 on 2022-02-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScreenTitle',
        ),
    ]
