# Generated by Django 4.0.2 on 2022-02-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_screentitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllHomeScreenComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.project')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.servicestitle')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.statsdetail')),
            ],
        ),
    ]
