# Generated by Django 4.0.2 on 2022-02-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_allhomescreencomponents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('program_icons', models.ImageField(blank=True, upload_to='programs_icon')),
            ],
        ),
    ]
