# Generated by Django 4.0.2 on 2022-02-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsdetail',
            name='stats_icons',
            field=models.ImageField(blank=True, upload_to='stats_icon'),
        ),
    ]
