# Generated by Django 4.0.2 on 2022-03-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_statsdetail_stats_icons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllHomeScreenComponents',
        ),
    ]
